// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schoolRegistration.Data;

namespace schoolRegistration.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190317154246_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("schoolRegistration.Models.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code");

                    b.Property<string>("corequisite_course");

                    b.Property<bool>("isMain");

                    b.HasKey("id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("schoolRegistration.Models.Registration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("course_id");

                    b.Property<int>("student_id");

                    b.HasKey("id");

                    b.HasIndex("course_id");

                    b.HasIndex("student_id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("schoolRegistration.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("schoolRegistration.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("schoolRegistration.Models.Registration", b =>
                {
                    b.HasOne("schoolRegistration.Models.Course", "Course")
                        .WithMany("Registrations")
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("schoolRegistration.Models.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
